### ISSUE TITLE
 why do you choose Preemptive

### ISSUE THREAD

**Issue by HoangNgo88** [nixmaniack/sjfp#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose preemptive in your project instead of cooperative multitasking, are there any special feature but others dont have Can you share me about it. I am wondering when I should choose preemptive in your project instead of cooperative multitasking

**Comment by nixmaniack** [comment]
Hi @HoangNgo88! 

What I had implemented was based on my learnings when I was in college studying these cpu scheduling algorithms. This is just one of the implementations of Shortest Job First with preemptive scheduling. 

I'm sure there are use-cases for both preemptive and cooperative multi-tasking but I didn't do any comparative study on them at that time.
